[pyprland]
plugins = [
  "scratchpads",
  "monitors",
  "toggle_dpms",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "80% 80%"
margin = 150

[scratchpads.volume]
animation = "fromTop"
command = "pavucontrol"
class = "pavucontrol"
lazy = true
size = "80% 80%"
margin = 150

[scratchpads.calc]
animation = "fromTop"
command = "qalculate-gtk"
class = "qalculate-gtk"
size = "80% 80%"
margin = 150

[scratchpads.music]
animation = "fromTop"
command = "sonixd"
class = "Sonixd"
size = "80% 80%"
margin = 150
process_tracking = false
