[pyprland]
plugins = [
  "scratchpads",
  "lost_windows",
  "monitors",
  "shift_monitors",
  "toggle_dpms",
  "magnify",
  "expose",
  "shift_monitors",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "80% 80%"
margin = 150

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "pavucontrol"
lazy = true
size = "80% 80%"
unfocus = "hide"

# [monitors]
# unknown = "wlrlui"

[monitors.placement]
"Acer".leftOf = "HDMI-0"
"Sony".topOf = "eDP-1"
