#!/usr/bin/env bash

bandwidth() {
    ethernet_if=$(ip -br addr show | sed -n '/enp/p' | sed 's/\ .*//' | head -n1)
    wifi_if=$(ip -br addr show | sed -n '/wlp/p' | sed 's/\ .*//' | head -n1)

    wifi_connected=$(nmcli -g GENERAL.STATE dev show "$wifi_if")
    if echo "$wifi_connected" | grep -q "^100"; then
        device="$wifi_if"
    else
        device="$ethernet_if"
    fi

    bytes=$(cat "/sys/class/net/$device/statistics/${1}_bytes")
    sleep 1
    new_bytes=$(cat "/sys/class/net/$device/statistics/${1}_bytes")
    bytes_diff=$((new_bytes - bytes))
    rate=$(numfmt --to=iec $bytes_diff)
    echo "$rate/s"
}

bandwidth "$@"
